# Generated by Django 3.2.5 on 2021-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('body', models.TextField(max_length=200, verbose_name='内容')),
                ('created', models.DateField(auto_now=True, verbose_name='作成日時')),
                ('updated', models.DateField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
