# Generated by Django 3.2.5 on 2021-07-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210708_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
